services:
  postgres:
    image: postgres:15.1
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: twh!@1234
      POSTGRES_DB: moving_db
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: DockerFile
    container_name: moving_app
    ports:
      - 3000:3000
    volumes:
      - ./:/app
      - /app/node_modules
    working_dir: /app
    environment:
      - DATABASE_URL=postgresql://postgres:twh!@1234@postgres:5432/moving_db?schema=public
    command: >
      sh -c "
        npm install &&
        sleep 5 &&
        npx prisma generate &&
        npx prisma migrate deploy &&
        npm run start:dev
      "
    depends_on:
      postgres:
        condition: service_healthy
